from enum import Enum


class ErrorCode(str, Enum):
    SUCCESS = "SUCCESS"
    BAD_REQUEST = "BAD_REQUEST"
    UNAUTHORIZED = "UNAUTHORIZED"
    FORBIDDEN = "FORBIDDEN"
    NOT_FOUND = "NOT_FOUND"
    VALIDATION_ERROR = "VALIDATION_ERROR"
    INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR"
    TOKEN_EXPIRED = "TOKEN_EXPIRED"
    INVALID_TOKEN = "INVALID_TOKEN"
    LOGIN_FAILED = "LOGIN_FAILED"
    STORE_ACCESS_DENIED = "STORE_ACCESS_DENIED"


class Role(str, Enum):
    OWNER = "owner"
    STORE_MANAGER = "store_manager"
