"""add auth audit log

Revision ID: 7d43bf92723d
Revises: 434dc225d8fb
Create Date: 2026-03-31 12:58:55.128220

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d43bf92723d'
down_revision: Union[str, Sequence[str], None] = '434dc225d8fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auth_audit_logs', sa.Column('email', sa.String(length=255), nullable=True))
    op.add_column('auth_audit_logs', sa.Column('event_type', sa.String(length=64), nullable=False))
    op.add_column('auth_audit_logs', sa.Column('result', sa.String(length=32), nullable=False))
    op.add_column('auth_audit_logs', sa.Column('reason_code', sa.String(length=64), nullable=True))
    op.drop_column('auth_audit_logs', 'reason')
    op.drop_column('auth_audit_logs', 'success')
    op.drop_column('auth_audit_logs', 'username')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auth_audit_logs', sa.Column('username', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.add_column('auth_audit_logs', sa.Column('success', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('auth_audit_logs', sa.Column('reason', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('auth_audit_logs', 'reason_code')
    op.drop_column('auth_audit_logs', 'result')
    op.drop_column('auth_audit_logs', 'event_type')
    op.drop_column('auth_audit_logs', 'email')
    # ### end Alembic commands ###
