"""empty message

Revision ID: c9ce03324e8b
Revises: 42ec348bce73
Create Date: 2026-03-29 19:06:33.477931

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c9ce03324e8b'
down_revision: Union[str, Sequence[str], None] = '42ec348bce73'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('orders')
    op.drop_table('occupancy_logs')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('occupancy_logs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('time', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('camera_id', sa.TEXT(), server_default=sa.text("'cam1'::text"), autoincrement=False, nullable=False),
    sa.Column('current_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('smoothed_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('raw_conf_avg', sa.NUMERIC(precision=5, scale=3), autoincrement=False, nullable=True),
    sa.Column('frame_rate', sa.NUMERIC(precision=6, scale=2), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('occupancy_logs_pkey'))
    )
    op.create_table('orders',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('customer_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('dish', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('order_time', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('orders_pkey'))
    )
    # ### end Alembic commands ###
